language: node_js
node_js:
  - "8"
  - "10"
jobs:
  include:
    - stage: Install
      script: npm install
    - stage: Build
      script: npm run build
    - stage: Test
      script: npm run test
